### ISSUE TITLE
Separate the extension into separate editions per region

### ISSUE THREAD

**Issue by dabockster** [selfagency/bs-detector#113] opened 2016-12-06 23:35 UTC
Judging by the massive worldwide influx of recommendations in #53, I think creating separate BS Detector "editions" for different regions should be considered. Basically, instead of having one massive list, we could create separate extensions for users in the United States, Europe, Asia, and Austraila and have each respective extension use its own list.

Another possibility is to have a setup prompt in the current extension that allows a user to select different BS lists to use.

**Comment by Bastlynn** [comment] 2016-12-07 01:49
This is a dupe of https://github.com/selfagency/bs-detector/issues/63 - we're looking at defaults by lang, and letting users pick one or more lists based on their own preferences.

**Closed** 2016-12-07 03:15 UTC
