### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by optomos** [selfagency/bs-detector#31] opened 2016-11-23 23:30 UTC
I've been noticing overall performance with Chrome in Facebook deteriorating over time and when I checked in task manager, the Chrome instance for B.S. Detector was consuming a lot of RAM  and continued to rise so I had to kill it, but before I did, I created a mini dump. The dump file is a little over 2GB so I can't attach it, but available if needed.

**Comment by selfagency** [comment] 2016-11-24 07:43
the last release had a big bug. i just pushed an update. let me know if that resolves it for you.

**Comment by selfagency** [comment] 2016-11-29 16:22
Duplicate of issue #50.

**Closed by selfagency** 2016-11-29 16:22 UTC
Labels: help wanted
