### ISSUE TITLE
Gmail lag

### ISSUE THREAD

**Issue by shortformblog** [selfagency/bs-detector#48] opened 2016-11-28 17:34 UTC
Hey there,

Your extension is a great idea, and as a journalist, I really like the idea behind it. But the app appears to be causing some significant slowdown in rich text editors, such as Gmail. I spent more than an hour this morning trying to figure out what was causing Gmail to be basically impossible to type in, and when I disabled this plugin, everything started working normally again. This issue is likely related to #47.

**Comment by lewisje** [comment] 2016-11-28 17:57
I believe I have found, and fixed, the issue, and I will put the fix into a new pull request once my pending PR is acted on: https://github.com/selfagency/bs-detector/issues/39#issuecomment-263196591

**Comment by selfagency** [comment] 2016-11-28 22:10
@lewisje @Bastlynn I just pushed an experimental work-in-progress to a branch called experimental (https://github.com/selfagency/bs-detector/tree/experimental) where I completely re-approach the way I'm targeting links and handling the MutationObserver. If you could, please take a look to see if you think it's an improvement over the previous method, or not, and if so, what I'm doing wrong that it's not firing right on Facebook. Thanks!

**Comment by lewisje** [comment] 2016-11-28 23:52
I don't have much of an opinion here; I'm thinking that the overhead of jQuery vs. superdom vs. built-in APIs isn't a big difference, but I'd need to profile the extension to be sure about that.

**Comment by selfagency** [comment] 2016-11-29 16:20
duplicate of issue #50

**Closed by selfagency** 2016-11-29 16:20 UTC
Labels: bug, duplicate
