### ISSUE TITLE
Causes severe lag on Teamwork.com

### ISSUE THREAD

**Issue by easycheese** [selfagency/bs-detector#47] opened 2016-11-28 16:38 UTC
Not sure why but this extension is definitely the culprit.  

Tested using fresh incognito mode:
1)  Try to create a new subtask, works fine, no lag
2)  Enabled this extension
3)  Try to create a new subtask, significant lag occurs on clicking buttons and even keyboard input.

Note that this teamwork site has multiple lists with hundreds of tasks.

**Comment by lewisje** [comment] 2016-11-28 17:56
I believe I have found, and fixed, the issue; if my current pull request is acted on, I will put the fix into a new pull request: https://github.com/selfagency/bs-detector/issues/39#issuecomment-263196591

**Comment by selfagency** [comment] 2016-11-29 16:20
duplicate of issue #50

**Closed by selfagency** 2016-11-29 16:20 UTC
Labels: bug, duplicate
