### ISSUE TITLE
Plugin Slows Down Browser Response Significantly (windows 10)

### ISSUE THREAD

**Issue by j9ac9k** [selfagency/bs-detector#39] opened 2016-11-27 22:04 UTC
Hello,

Thanks for making this plugin.  I am running Windows 10, Chrome 54.0.2840.99 m (64-bit), and 0.2.3 version of the extension.  With the extension loaded, I get massive slowdowns when using my instance of [RStudio Server](https://www.rstudio.com/products/rstudio/).  I suspected slow-downs on other websites as well, but given the amount of text entry I make in the RStudio web instance, the slow-downs are quite apparent (and they go away when disabling the extension and reloading the page).

Unfortunately I'm not sure what information is relevant here for you to diagnose this issue.  Let me know what information I can provide and I'll be happy to do so.

**Comment by lewisje** [comment] 2016-11-28 06:55
I'm guessing it's because the `MutationObserver` looks through all links every time it's triggered, which is every time the body is changed.

I made some improvements in a pull request, but I haven't looked into how the `MutationObserver` works in particular.

One idea I had was to have it work only on the added or changed nodes, instead of the entire body; another idea is to throttle it, so it can't run more than once every 100 milliseconds or so.

**Comment by j9ac9k** [comment] 2016-11-28 16:03
@lewisje thanks for the detailed reply.  Is there anything I can test on my end?

**Comment by lewisje** [comment] 2016-11-28 17:11
Download the ZIP file for [my fork](https://github.com/lewisje/bs-detector), copy the "chrome" subdirectory to some known-safe place (maybe your user profile directory), rename it "bs-detector", make the change to "inject.js" that I mentioned above (in my fork, [the relevant lines to replace are from 222 to 247](https://github.com/lewisje/bs-detector/blob/master/chrome/js/inject.js#L222)), and install the extension from this "bs-detector" directory as an unpacked extension; then see whether it still causes RStudio Server to slow down.

**Comment by j9ac9k** [comment] 2016-11-28 17:18
Thanks for the instructions!  I'll give it a go when I get home tonight and report back.

**Comment by selfagency** [comment] 2016-11-29 04:59
I just pushed the latest version to the Chrome Store. Should be live within the hour.

**Comment by NeonRonin** [comment] 2016-11-29 14:46
Unfortunately, the input lag is just as bad with version 0.2.4. Disabling BS detector continues to resolve the issue.

**Comment by selfagency** [comment] 2016-11-29 14:54
Ok, I think I'm going to have to restrict the plugin to Facebook and Twitter and slowly expand it to other social media sites and online services so where can target their content containers specifically instead of the whole document body. I'll work on that and push an update.

**Comment by selfagency** [comment] 2016-11-29 16:20
duplicate of issue #50

**Closed by selfagency** 2016-11-29 16:20 UTC
Labels: bug, duplicate
